### ISSUE TITLE
Create a logo for TheLeanProgrammer

### ISSUE THREAD

**Issue by MadhavBahl** [TheLeanProgrammer/TheLeanProgrammer.github.io#2]

**Comment by MadhavBahl** [comment]
@reallinfo would you like to work on it?

**Comment by reallinfo** [comment]
Hi @MadhavBahlMD 

I designed a logo. how does this look?

![tlp](https://user-images.githubusercontent.com/36298335/47585781-faa7e980-d966-11e8-8292-537a43cea1a3.jpg)

**Comment by reallinfo** [comment]
you can also say if you have an idea.

**Comment by MadhavBahl** [comment]
Thanks alot for your contributions @reallinfo , you are a great designer 💯 
This looks amazing, 😃 ❤️ 

But the letter "P" is looking little odd, I'll think of some new ideas as well.

**Comment by MadhavBahl** [comment]
How about removing the letter "P" from the logo?

**Comment by reallinfo** [comment]
Sure, 

![lp2](https://user-images.githubusercontent.com/36298335/47610054-6a47d280-da54-11e8-9be1-bf16c0df7cfa.jpg)


I have a new idea.

![lp](https://user-images.githubusercontent.com/36298335/47610031-d118bc00-da53-11e8-80bb-b25c7ac4e74b.jpg)

**Comment by MadhavBahl** [comment]
Great 🌟 

You can make a PR 😃

**Comment by reallinfo** [comment]
Thanks,  which version should I send a pr? Also, I would also be pleased if you add a license at to your a free time to this repo. Thank you for trust me. <3

**Comment by MadhavBahl** [comment]
@reallinfo  Can you send PNGs of both versions? 

Also, for the license, should I use MIT? I'll add credits to your logo in the README as well as License file.

**Comment by reallinfo** [comment]
Yeah, MIT license is good idea. I sent a pr. Thank you Madhav!
